In [3]:
import sys, os
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv(r'Q:\Data\Surveys\HouseholdSurveys\MTC-SFCTA2018\Processing_20210302\Map Matching\output\paths.csv')

C:\Users\drew\AppData\Local\Temp\ipykernel_1224\934012752.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'Q:\Data\Surveys\HouseholdSurveys\MTC-SFCTA2018\Processing_20210302\Map Matching\output\paths.csv')

In [10]:
bb = [321181,587008
]

In [5]:
df.head()

,point_id,index,m_lat,m_lon,mode_type,accuracy,heading,speed,collected_at,hh_id,person_id,trip_id,edge,source,target,reversed,c_lat,c_lon,loc,meters
0,300021,0,37.786485,-122.44522,3,4.0,260.0,11.0,2019-02-10 08:32:54,181038050,18103805001,18103805001001,140955,116825,127705,0,37.78649,-122.44517,0.0,4.423803
1,300022,0,NaN,NaN,3,4.0,200.0,13.0,2019-02-10 08:33:17,181038050,18103805001,18103805001001,510778,116825,436639,0,NaN,NaN,NaN,NaN
2,300022,0,NaN,NaN,3,4.0,200.0,13.0,2019-02-10 08:33:17,181038050,18103805001,18103805001001,616387,436639,492508,0,NaN,NaN,NaN,NaN
3,300022,0,NaN,NaN,3,4.0,200.0,13.0,2019-02-10 08:33:17,181038050,18103805001,18103805001001,679522,492508,263101,0,NaN,NaN,NaN,NaN
4,300022,0,37.78534,-122.447591,3,4.0,200.0,13.0,2019-02-10 08:33:17,181038050,18103805001,18103805001001,264278,263101,262727,0,37.78535,-122.44761,0.460967,1.917586

In [11]:
df.loc[df['hh_id'].eq(181082947) & df['edge'].isin(bb)]

,point_id,index,m_lat,m_lon,mode_type,accuracy,heading,speed,collected_at,hh_id,person_id,trip_id,edge,source,target,reversed,c_lat,c_lon,loc,meters
1890341,612568,895,NaN,NaN,9,65.0,41.0,-1.0,2018-11-24 13:56:46,181082947,18108294701,18108294701003,321181,321834,321209,0,NaN,NaN,NaN,NaN
1890855,612683,897,37.806621,-122.368907,9,10.0,220.0,11.0,2018-11-24 20:10:36,181082947,18108294701,18108294701005,587008,255809,339000,0,37.80656,-122.36885,0.07467,8.255279
1899825,614271,969,NaN,NaN,9,10.0,221.0,25.0,2018-11-30 23:18:59,181082947,18108294701,18108294701077,587008,255809,339000,0,NaN,NaN,NaN,NaN